[package]
name = "common"
version = "0.1.0"
edition = "2021"

[dependencies]
# shared dependencies
chrono = { workspace = true }
clap = { workspace = true }
error-chain = { workspace = true }
fern = { workspace = true }
log = { workspace = true }
