name: Servers Build & Test

on:
  push:
    branches: [ "main" ]
    paths:
      - '.github/**'
      - 'Cargo.lock'
      - 'Cargo.toml'
      - 'protos/**'
      - 'server/**'
  pull_request:
    branches: [ "main" ]
    paths:
      - '.github/**'
      - 'Cargo.lock'
      - 'Cargo.toml'
      - 'protos/**'
      - 'server/**'

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    
    - name: Install Protoc
      uses: arduino/setup-protoc@v2
      with:
        version: "23.x"

    - name: ⚡ Cache
      uses: actions/cache@v3
      with:
        path: |
          ~/.cargo/registry
          ~/.cargo/git
          target
        key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}
    
    - name: 🏗️ Build
      run: cargo build --verbose
    
    - name: ✅ Tests
      run: cargo test --verbose
